export enum CommonSettingNameEnum {
  GAS_PS_SIGN = 'GAS_PS_SIGN',
  SMEV_SIGN = 'SMEV_SIGN',
  GAS_PS_MESSAGE_RECEIVE_URL = 'GAS_PS_MESSAGE_RECEIVE_URL',
  SMEV_SEND_MESSAGE_URL = 'SMEV_SEND_MESSAGE_URL',
  GAS_PS_SIGN_PASS = 'GAS_PS_SIGN_PASS',
}
