export enum SpvMethodNameEnum {
  StatCardDownload = 'StatCardDownload',
  StatCardUpload = 'StatCardUpload',
  StatCardStatus = 'StatCardStatus',
  StatCardRevocation = 'StatCardRevocation',
  StatCardList = 'StatCardList',
  CanceledStatCard = 'CanceledStatCard',
  KUSPPackageStatus = 'KUSPPackageStatus',
  KUSPRecordStatus = 'KUSPRecordStatus',
  KUSPRecordDecisions = 'KUSPRecordDecisions',
  KUSPPackageUpload = 'KUSPPackageUpload',
  TransferStatCard1 = 'TransferStatCard 1',
  TransferStatCard2 = 'TransferStatCard 2',
  TransferStatCard3 = 'TransferStatCard 3',
  FormsOnDate = 'FormsOnDate',
  FormVersionMetadata = 'FormVersionMetadata',
  DownloadDictionary = 'DownloadDictionary',
  FLCMetadata = 'FLCMetadata',
  LawOrganList = 'LawOrganList',
  GetReport = 'GetReport',
  GetReportList = 'GetReportList',
}
